name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies (core)
        working-directory: packages/core
        run: |
          yarn
      - name: Check lint (core)
        working-directory: packages/core
        run: |
          yarn lint
      - name: Test (core)
        working-directory: packages/core
        run: |
          yarn test
      - name: Build (core)
        working-directory: packages/core
        run: |
          yarn build
      - name: Install dependencies (web)
        working-directory: packages/web
        run: |
          yarn
      - name: Check lint (web)
        working-directory: packages/web
        run: |
          yarn lint
      - name: Build (web)
        working-directory: packages/web
        run: |
          yarn build
      - name: Upload artifact (web)
        uses: actions/upload-artifact@v3
        with:
          name: Build output
          path: packages/web/dist
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: Build output
          path: dist
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          cname: minesweeper.s7a.dev
